name: backend-local

services:
  app:
    container_name: backend-local-docker
    env_file:
      - .env
    ports:
      - 3010:3010
    volumes:
      - ./:/usr/src/app
      - /var/log/ssd:/var/log/ssd
    networks:
      - backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: "${HEALTH_CMD} \"{\\\"content\\\": \\\"\"backend-standalone-app-status=$(curl -o /dev/null -s -w \"%{http_code}\" http://127.0.0.1:3010/api)\"\\\"}\" ${DISCORD_WEBHOOK_URL}"
      interval: 300s
      timeout: 30s
      retries: 5
      start_period: 30s
    
networks:
  backend:
    external:
      name: backend
    driver: bridge
    attachable: true
    driver_opts:
      com.docker.network.bridge.name: backend