pipeline {
    agent {
        docker {
            image 'composer:latest'
            args '-v $WORKSPACE:/workspace -w /workspace/Lab7a/jenkins-phpunit-test'
        }
    }
    stages {
        stage('Build') {
            steps {
                dir('Lab7a/jenkins-phpunit-test') {
                    sh 'composer install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('Lab7a/jenkins-phpunit-test') {
                    sh './vendor/bin/phpunit tests'
                }
            }
        }
    }
}
